# Generated by Django 6.0.2 on 2026-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_land_contact_email_land_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Phone number for booking confirmations', max_length=20, null=True),
        ),
    ]
