# Generated by Django 6.0.2 on 2026-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_reservation_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for anonymous bookings', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for anonymous bookings', max_length=100),
        ),
    ]
