# Generated by Django 4.2.29 on 2026-03-17 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lands", "0008_land_pricing_reservation_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="max_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum rental period in days (leave blank for no limit)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="min_duration_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum rental period in days (rent listings only)",
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="monthly_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% discount for bookings of 1+ month (rent only)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Base price", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="weekly_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% discount for bookings of 1+ week (rent only)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="agreed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final agreed price for this booking",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date of rental period", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Start date of rental period", null=True
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "land",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lands.land",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
