# Generated by Django 4.2.29 on 2026-03-18 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lands", "0009_alter_land_max_duration_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="GPS latitude for map pin", null=True
            ),
        ),
        migrations.AddField(
            model_name="land",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="GPS longitude for map pin", null=True
            ),
        ),
        migrations.AddField(
            model_name="land",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of detail page views"
            ),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="lands.land",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "land")},
            },
        ),
    ]
