# Generated by Django 4.2.30 on 2026-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0012_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['land', 'status', 'start_date', 'end_date'], name='lands_reser_land_id_c0ff64_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['land', 'customer'], name='lands_reser_land_id_b19b67_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer_email'], name='lands_reser_custome_336e6e_idx'),
        ),
    ]
