# Generated by Django 4.2.30 on 2026-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0014_add_terrain_and_utilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class (e.g., FontAwesome)', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Utilities',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='land',
            old_name='image',
            new_name='land_image_path',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='listing_type',
            new_name='usage',
        ),
        migrations.RemoveField(
            model_name='land',
            name='has_electricity',
        ),
        migrations.RemoveField(
            model_name='land',
            name='has_water',
        ),
        migrations.RemoveField(
            model_name='land',
            name='is_cleared',
        ),
        migrations.RemoveField(
            model_name='land',
            name='is_fenced',
        ),
        migrations.RemoveField(
            model_name='land',
            name='road_access',
        ),
        migrations.DeleteModel(
            name='LandImage',
        ),
        migrations.AddField(
            model_name='land',
            name='utilities',
            field=models.ManyToManyField(blank=True, help_text='Select all available utilities and improvements', related_name='lands', to='lands.utility'),
        ),
    ]
