# Generated by Django 4.2.30 on 2026-04-23 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0015_utility_rename_image_land_land_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='additional_utilities_notes',
            field=models.TextField(blank=True, help_text='Additional notes on utilities not mentioned above', null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='land_id',
            field=models.CharField(blank=True, help_text='Unique reference ID (e.g. LR-001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_records', to='lands.land'),
        ),
    ]
