# Generated by Django 4.2.30 on 2026-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0017_alter_message_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='requested_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size requested by customer (if partial)', max_digits=10, null=True),
        ),
    ]
