# Generated by Django 4.2.30 on 2026-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0018_reservation_requested_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='soil_fertility',
            field=models.CharField(blank=True, choices=[('very_low', 'Very Low — Degraded / Sandy'), ('low', 'Low — Needs Improvement'), ('moderate', 'Moderate — Average'), ('high', 'High — Fertile'), ('very_high', 'Very High — Rich Volcanic / Alluvial')], default='moderate', help_text='Soil fertility level — used for automatic crop suggestions', max_length=20),
        ),
    ]
