# Generated by Django 4.2.30 on 2026-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0019_land_soil_fertility'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='district',
            field=models.CharField(blank=True, help_text='Wilaya', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='region',
            field=models.CharField(blank=True, choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pwani', 'Pwani'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga')], help_text='Mkoa', max_length=30),
        ),
        migrations.AddField(
            model_name='land',
            name='street',
            field=models.CharField(blank=True, help_text='Mtaa / Kijiji', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='ward',
            field=models.CharField(blank=True, help_text='Kata', max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
