# Generated by Django 4.2.30 on 2026-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0020_land_district_land_region_land_street_land_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this land listing is a draft'),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
