# Generated by Django 4.2.30 on 2026-05-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lands', '0021_land_is_draft_alter_land_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='lands/gallery/')),
                ('position', models.CharField(choices=[('north', 'North View'), ('south', 'South View'), ('east', 'East View'), ('west', 'West View'), ('aerial', 'Aerial View'), ('from_above', 'From Above'), ('vertical', 'Vertical View'), ('horizontal', 'Horizontal / Panoramic'), ('front', 'Front View'), ('other', 'Other')], default='other', help_text='Direction / angle from which the photo was taken', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Optional short description of this photo', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Use as the cover / thumbnail image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.land')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Land Image',
                'verbose_name_plural': 'Land Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
