# Generated by Django 4.2.30 on 2026-05-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0022_landimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='max_duration_days',
        ),
        migrations.RemoveField(
            model_name='land',
            name='min_duration_days',
        ),
    ]
