# Generated by Django 4.2.30 on 2026-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0023_remove_land_max_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price', max_digits=12, null=True),
        ),
    ]
