# Generated by Django 4.2.30 on 2026-05-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0024_alter_land_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='wizard_step',
            field=models.PositiveIntegerField(default=1, help_text='The current step in the registration wizard'),
        ),
    ]
