# Generated by Django 4.2.30 on 2026-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0025_land_wizard_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='True if owner has confirmed receipt of funds'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Upload proof of payment (screenshot/receipt)', null=True, upload_to='payments/receipts/'),
        ),
    ]
