# Generated by Django 4.2.30 on 2026-05-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lands', '0026_reservation_payment_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigopesa', 'Tigo Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash on Arrival')], max_length=20, null=True)),
                ('payment_reference', models.CharField(max_length=100)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='payments/receipts/')),
                ('payment_date', models.DateField(help_text='Date when this installment was paid')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('confirmed_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lands.reservation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
