# Generated by Django 4.2.30 on 2026-05-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0027_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='platform_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='platform_fee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
