# Generated by Django 4.2.30 on 2026-06-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0028_paymentrecord_platform_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
