# Generated by Django 4.2.30 on 2026-06-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0016_landreport'),
        ('lands', '0029_alter_reservation_status'),
    ]

    operations = [
    ]
