# Generated by Django 4.2.30 on 2026-06-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lands', '0030_merge_0016_landreport_0029_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='landreport',
            name='unique_land_report_per_user',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='owner_received_on',
            field=models.DateTimeField(blank=True, help_text='When the owner confirmed receipt of released funds', null=True),
        ),
        migrations.AlterField(
            model_name='landreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='True if admin has confirmed the customer payment'),
        ),
        migrations.AlterUniqueTogether(
            name='landreport',
            unique_together={('land', 'reported_by')},
        ),
    ]
