# Generated by Django 4.2.30 on 2026-06-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_operatorpaymentconfig_created_by_and_more'),
        ('lands', '0031_remove_landreport_unique_land_report_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='selected_operator_payment',
            field=models.ForeignKey(blank=True, help_text='Operator payment method chosen by customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_reservations', to='accounts.operatorpaymentconfig'),
        ),
    ]
