# Generated by Django 4.2.30 on 2026-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0032_reservation_selected_operator_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='owner_account_identifier',
            field=models.CharField(blank=True, help_text='Owner payout identifier (M-Pesa number / bank account)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Cached owner email for payout', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Cached owner full name for payout', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='owner_payment_method',
            field=models.CharField(blank=True, help_text='Owner preferred payout method at confirmation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Cached owner phone for payout', max_length=30, null=True),
        ),
    ]
