# Generated by Django 4.2.30 on 2026-06-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0034_add_owner_will_refund'),
        ('lands', '0034_land_owner_will_refund'),
    ]

    operations = [
    ]
