# Generated by Django 4.2.30 on 2026-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0035_merge_20260616_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Customer reason for refund request'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_requested',
            field=models.BooleanField(default=False, help_text='True if the customer has requested a refund'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
