# Generated by Django 4.2.29 on 2026-03-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_govt_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kyc_document",
            field=models.FileField(
                blank=True,
                help_text="ID / Land title / ownership proof document",
                null=True,
                upload_to="kyc/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kyc_notes",
            field=models.TextField(blank=True, help_text="Admin notes on KYC review"),
        ),
    ]
