# Generated by Django 4.2.30 on 2026-04-24 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options_remove_user_bio_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='govt_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='govt_letter_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ownership_proof',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
