# Generated by Django 4.2.30 on 2026-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options_remove_user_govt_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
