# Generated by Django 4.2.30 on 2026-05-15 08:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
    ]
